
project 'ZHSegmentTagView Example.xcodeproj'
platform :ios, '8.0'

target 'ZHSegmentTagView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZHSegmentTagView
  pod 'Masonry'
end

